name: paygo
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  icons_launcher: ^3.0.1
  firebase_core: ^3.15.1
  flutter_riverpod: ^2.6.1
  firebase_crashlytics: ^4.3.9
  easy_localization: ^3.0.7+1
  go_router: ^16.0.0
  flutter_cache_manager: ^3.4.1
  flutter_secure_storage: ^9.2.4
  toastification: ^3.0.3
  permission_handler: ^12.0.1
  firebase_messaging: ^15.2.9
  flutter_local_notifications: ^19.3.0
  dio: ^5.8.0+1
  logger: ^2.6.0
  lottie: ^3.3.1
  http: ^1.4.0
  flutter_svg: ^2.2.0
  url_launcher: ^6.3.2
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  geolocator: ^14.0.2
  avatar_glow: ^3.0.1
  expansion_tile_card: ^3.0.0
  in_app_review: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


icons_launcher:
  image_path: "assets/images/logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lotties/ 
    - assets/translations/  
    - assets/sounds/   

  fonts:
    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish-Regular.ttf
    - family: Number
      fonts:
        - asset: assets/fonts/FE-FONT.ttf
